management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain

  servlet:
    context-path: /api

info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'

# Configuración de la base de datos
spring:
  datasource: # Configuración de la conexión a la base de datos
    url: jdbc:mysql://localhost:3310/flights_reservation
    username: root
    password: muppet